In [94]:
import numpy as np

In [11]:
# 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a=np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [12]:
# 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [24]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [26]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [33]:
# 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
np.reshape(a,(2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
np.reshape(a,(4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [40]:
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.reshape(a,(-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
np.reshape(a,(-1,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [1]:
# 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# нет,это двумерный массив


In [6]:
# 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
# со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
a=np.random.randn(3,4)
a

array([[-0.22450417, -1.75497699, -0.03734928, -0.61877276],
       [ 0.59358454,  0.98473588,  0.56323189,  0.01055206],
       [-0.196817  , -1.85030927,  0.04881328,  0.61949026]])

In [7]:
a=a.flatten()
a

array([-0.22450417, -1.75497699, -0.03734928, -0.61877276,  0.59358454,
        0.98473588,  0.56323189,  0.01055206, -0.196817  , -1.85030927,
        0.04881328,  0.61949026])

In [9]:
# # 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
# В чем разница между массивами a и b?
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [13]:
b=a.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [ ]:
# a-это одномернный массив, в-это двумерный массив

In [21]:
# # 7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
# число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
# массива b, состоящего из единиц.
# Итоговый массив v должен иметь атрибут size, равный 10.
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
b=np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [22]:
v=np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [23]:
v.size

10

In [ ]:
# 8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
# 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
# Какой размер имеет матрица B?
# Получится ли вычислить обратную матрицу для матрицы B и почему?

In [18]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
A=a.reshape(4,3)
A


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
At=A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [21]:
B=np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [22]:
B.shape


(4, 4)

In [15]:
B_inv=np.linalg.inv(B)
# Получится ли вычислить обратную матрицу для матрицы B и почему?
Для матрицы В вычислить обратную матрицу невозможно, так как это сингулярная матрица и ее определитель равен 0.

SyntaxError: invalid syntax (<ipython-input-15-c405fb7e202e>, line 3)

In [46]:
np.linalg.det(B)

0.0

In [51]:
# 9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
# Поменяйте его форму так, чтобы получилась квадратная матрица C.
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
np.random.seed(42)

In [25]:
a=np.random.randint(0,16,16)
a

array([13,  1,  2,  8,  1, 12,  6, 14,  1,  6,  7, 12,  2,  6, 12, 13])

In [26]:
C=a.reshape(4,4)
C

array([[13,  1,  2,  8],
       [ 1, 12,  6, 14],
       [ 1,  6,  7, 12],
       [ 2,  6, 12, 13]])

In [27]:
D=B+C*10
D

array([[135,  24,  43, 112],
       [ 24, 170, 146, 262],
       [ 33, 146, 219, 332],
       [ 52, 182, 332, 432]])

In [66]:
np.linalg.det(D)

-120236799.99999988

In [69]:
np.linalg.matrix_rank(D)

4

In [49]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00759231,  0.00460807, -0.01610309,  0.00761244],
       [-0.00047231,  0.01962003, -0.02948037,  0.01087948],
       [-0.00154254,  0.00243934, -0.02956109,  0.02163874],
       [ 0.00047056, -0.0106952 ,  0.03707655, -0.01981476]])

In [101]:
# 10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
# Убедитесь, что в матрице D_inv остались только нули и единицы.
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
# а матрицы B и C - в качестве источников данных,
# получите матрицу E размером 4x4. 
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
# должны быть равны соответствующему элементу матрицы B,
# а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
# должны быть равны соответствующему элементу матрицы C.


In [55]:
np.where(D_inv<0,0,1)



array([[1, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [97]:
E=np.where(D_inv>0,B,C)
E

array([[  5,  14,   2,  32],
       [  1,  50,   6, 122],
       [  1,  86,   7, 212],
       [ 32,   6, 212,  13]])

In [106]:
#  Задание 2
# Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
# Будем считать, что каждый столбец - это признак, а строка - наблюдение.
# Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
# Результат запишите в массив mean_a, в нем должно быть 2 элемента.
b=(1,2,3,3,1)
c=(6,8,11,10,7)
a=np.vstack((b,c))
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [107]:
a=a.reshape(5,2)
a


array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [109]:
mean_a=np.mean(a,axis=0)
mean_a

array([4.6, 5.8])

In [ ]:
# Задание 3
# Вычислите массив a_centered, отняв от значений массива а 
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.

In [110]:
a_centered=a-mean_a
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

In [89]:
# Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [138]:
a=a_centered[:5,:1]
a

array([[-3.6],
       [-1.6],
       [-3.6],
       [ 3.4],
       [ 5.4]])

In [165]:
a=np.squeeze(a)
a

array([-3.6, -1.6, -3.6,  3.4,  5.4])

In [151]:
b=a_centered[:5,1:]
b

array([[-3.8],
       [-2.8],
       [ 0.2],
       [ 5.2],
       [ 1.2]])

In [166]:
b=np.squeeze(b)
b

array([-3.8, -2.8,  0.2,  5.2,  1.2])

In [167]:
a_centered_sp=np.dot(a,b)
a_centered_sp

41.60000000000001

In [168]:
a_centered.shape

(5, 2)

In [169]:
N=5

In [171]:
a_centered_sp/(N-1)

10.400000000000002